/* ============================================================================
   OmniSource — core.js
   ----------------------------------------------------------------------------
   The shared brain of the site: theme, clipboard, toasts, formatting helpers,
   the global search engine + ⌘K palette (with history and popular searches),
   PWA plumbing (service worker, install prompt) and scroll-reveal motion.

   Loaded by every page, including the static app detail pages generated by
   src/omnisource/app_pages.py. It is dependency-free, works offline (all data
   it needs is cached by sw.js) and never blocks first paint (deferred).

   Page-specific rendering lives in js/site.js (home / compare / status /
   analytics / install / search).
   ========================================================================== */
(function () {
  'use strict';

  /* ------------------------------------------------------------------ root */
  // Resolve the site root from a loaded asset URL. `document.currentScript`
  // is null for deferred scripts (every page loads core.js with `defer`),
  // so we look the tag up in the DOM instead. Falling back to the pathname
  // keeps GitHub Pages project sites (/OmniSource/) working even if the
  // script tag is rewritten.
  function detectRoot() {
    function fromUrl(value, needle) {
      if (!value) return '';
      try { value = new URL(value, location.href).href; } catch (e) { return ''; }
      var idx = value.lastIndexOf(needle);
      return idx === -1 ? '' : value.slice(0, idx);
    }
    var scripts = document.getElementsByTagName('script');
    for (var i = 0; i < scripts.length; i++) {
      var rooted = fromUrl(scripts[i].src, '/js/core.js');
      if (rooted) return rooted.replace(/\/+$/, '');
    }
    var links = document.querySelectorAll('link[rel="stylesheet"]');
    for (var j = 0; j < links.length; j++) {
      var fromCss = fromUrl(links[j].href, '/assets/design-system/');
      if (fromCss) return fromCss.replace(/\/+$/, '');
    }
    var path = (location.pathname || '/').replace(/\/index\.html$/, '');
    path = path.replace(/\/(compare|status|analytics|install|search)(\/.*)?$/, '');
    path = path.replace(/\/apps\/[^/]+(\/.*)?$/, '');
    path = path.replace(/\/+$/, '');
    return path ? location.origin + path : location.origin;
  }
  var ROOT = detectRoot();
  function url(path) {
    if (!path) return '#';
    if (/^https?:\/\//.test(path)) return path;
    return ROOT + (path.charAt(0) === '/' ? path : '/' + path);
  }
  function asset(name) {
    var file = String(name || 'OmniSource.png').replace(/^assets\//, '');
    return url('assets/' + file);
  }

  /* --------------------------------------------------------------- helpers */
  var $ = function (sel, root) { return (root || document).querySelector(sel); };
  var $$ = function (sel, root) { return Array.prototype.slice.call((root || document).querySelectorAll(sel)); };

  var OS = {
    ROOT: ROOT,
    url: url,
    asset: asset,
    $: $,
    $$: $$,
    animateCount: animateCount,
    reducedMotion: window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches,

    esc: function (value) {
      return String(value == null ? '' : value).replace(/[&<>'"]/g, function (ch) {
        return { '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[ch];
      });
    },

    cleanUrl: function (value) {
      try {
        var u = new URL(value, location.href);
        return ['http:', 'https:'].indexOf(u.protocol) !== -1 ? u.href : '#';
      } catch (e) { return '#'; }
    },

    parseDate: function (value) {
      if (!value) return null;
      var d = new Date(String(value).length === 10 ? String(value) + 'T12:00:00Z' : value);
      return isNaN(d.valueOf()) ? null : d;
    },

    fmtDate: function (value) {
      var d = OS.parseDate(value);
      return d
        ? d.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })
        : (value || 'Unknown');
    },

    timeAgo: function (value) {
      var d = OS.parseDate(value);
      if (!d) return 'Unknown';
      var days = Math.max(0, Math.round((Date.now() - d.getTime()) / 86400000));
      if (days === 0) return 'today';
      if (days === 1) return 'yesterday';
      if (days < 30) return days + 'd ago';
      if (days < 365) return Math.round(days / 30) + 'mo ago';
      return Math.round(days / 365) + 'y ago';
    },

    fmtBytes: function (bytes) {
      if (!Number(bytes)) return 'Unknown';
      var units = ['B', 'KB', 'MB', 'GB'];
      var i = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
      return (bytes / Math.pow(1024, i)).toFixed(i > 1 ? 1 : 0) + ' ' + units[i];
    },

    fetchJSON: function (path, timeoutMs) {
      var controller = new AbortController();
      var id = setTimeout(function () { controller.abort(); }, timeoutMs || 8000);
      return fetch(url(path), { signal: controller.signal, headers: { Accept: 'application/json' } })
        .then(function (res) { return res.ok ? res.json() : null; })
        .catch(function () { return null; })
        .finally(function () { clearTimeout(id); });
    },

    toast: function (message) {
      var node = $('#toast');
      if (!node) {
        // Pages that do not ship the toast markup (favorites / collections)
        // still get the same shared component, created once on demand.
        node = document.createElement('div');
        node.className = 'toast';
        node.id = 'toast';
        node.setAttribute('role', 'status');
        node.setAttribute('aria-live', 'polite');
        node.innerHTML = '<svg aria-hidden="true" viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg><span></span>';
        document.body.appendChild(node);
      }
      var label = node.querySelector('span');
      if (label) label.textContent = message;
      node.classList.add('show');
      clearTimeout(OS._toastTimer);
      OS._toastTimer = setTimeout(function () { node.classList.remove('show'); }, 2600);
    },

    copy: function (text, successMsg) {
      function fallback() {
        var input = document.createElement('textarea');
        input.value = text;
        input.style.cssText = 'position:fixed;opacity:0';
        document.body.appendChild(input);
        input.select();
        try { document.execCommand('copy'); } catch (e) { /* ignore */ }
        input.remove();
        OS.toast(successMsg || 'Copied to clipboard');
      }
      if (navigator.clipboard && navigator.clipboard.writeText) {
        navigator.clipboard.writeText(text).then(
          function () { OS.toast(successMsg || 'Copied to clipboard'); },
          fallback
        );
      } else {
        fallback();
      }
    }
  };
  window.OS = OS;

  /* ----------------------------------------------------------------- theme */
  var THEMES = ['auto', 'light', 'dark'];
  function currentTheme() {
    return document.documentElement.dataset.theme || 'auto';
  }
  function setTheme(theme) {
    if (THEMES.indexOf(theme) === -1) theme = 'auto';
    document.documentElement.dataset.theme = theme;
    try { localStorage.setItem('omnisource-theme', theme); } catch (e) { /* private mode */ }
    var meta = $('#themeColor');
    if (meta) {
      var prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
      var dark = theme === 'dark' || (theme === 'auto' && prefersDark);
      meta.content = dark ? '#07070f' : '#e8eef8';
    }
    var btn = $('#themeButton');
    if (btn) {
      var labels = { auto: 'Theme: system', light: 'Theme: light', dark: 'Theme: dark' };
      btn.title = labels[theme];
      btn.setAttribute('aria-label', labels[theme] + '. Change color theme');
    }
  }
  function cycleTheme() {
    setTheme(THEMES[(THEMES.indexOf(currentTheme()) + 1) % THEMES.length]);
  }

  /* --------------------------------------------------------------- clipboard */
  document.addEventListener('click', function (event) {
    var target = event.target.closest ? event.target.closest('[data-copy]') : null;
    if (!target) return;
    OS.copy(target.getAttribute('data-copy') || '', target.getAttribute('data-copy-msg'));
  });

  /* ============================================================================
     Search engine — weighted fuzzy matching over the generated search index.
     Same contract as feeds/search-index.json (Fuse.js compatible): name,
     shortDescription, description, category, tags, developer, bundleId.
     ========================================================================== */
  var SEARCH_KEYS = [
    { name: 'name', weight: 0.35 },
    { name: 'shortDescription', weight: 0.15 },
    { name: 'description', weight: 0.10 },
    { name: 'category', weight: 0.08 },
    { name: 'tags', weight: 0.10 },
    { name: 'developer', weight: 0.10 },
    { name: 'bundleId', weight: 0.12 }
  ];
  var SEARCH_THRESHOLD = 0.38;
  var SEARCH_MIN_CHARS = 2;

  var Search = {
    docs: [],          // index documents
    trending: null,    // feeds/trending.json (for "popular" chips)
    ready: null,       // promise

    load: function () {
      if (!this.ready) {
        this.ready = OS.fetchJSON('feeds/search-index.json').then(function (doc) {
          Search.docs = (doc && doc.documents) || [];
          return Search.fetchTrending().then(function () { return Search.docs; });
        });
      }
      return this.ready;
    },

    fetchTrending: function () {
      return OS.fetchJSON('feeds/trending.json', 5000).then(function (doc) {
        Search.trending = doc;
        return doc;
      });
    },

    score: function (query, value) {
      if (!value) return 0;
      var text = String(value).toLowerCase();
      if (!text) return 0;
      if (text === query) return 1;
      if (text.indexOf(query) === 0) return 0.85;
      if (text.indexOf(query) !== -1) return 0.65;
      var tokens = query.split(/\s+/).filter(Boolean);
      if (!tokens.length) return 0;
      var hits = 0;
      for (var i = 0; i < tokens.length; i++) {
        if (text.indexOf(tokens[i]) !== -1) hits++;
      }
      if (!hits) return 0;
      return 0.45 * (hits / tokens.length);
    },

    search: function (query) {
      var q = String(query || '').toLowerCase().trim();
      if (q.length < SEARCH_MIN_CHARS) return [];
      var results = [];
      for (var i = 0; i < this.docs.length; i++) {
        var doc = this.docs[i];
        var score = 0;
        for (var k = 0; k < SEARCH_KEYS.length; k++) {
          var key = SEARCH_KEYS[k];
          var field = doc[key.name];
          if (Array.isArray(field)) {
            for (var f = 0; f < field.length; f++) {
              score += key.weight * this.score(q, field[f]);
            }
          } else {
            score += key.weight * this.score(q, field || '');
          }
        }
        if (score >= SEARCH_THRESHOLD) results.push({ doc: doc, score: score });
      }
      results.sort(function (a, b) { return b.score - a.score; });
      return results.slice(0, 10);
    },

    highlight: function (text, query) {
      var value = OS.esc(text);
      if (!query) return value;
      var parts = String(query).split(/\s+/).filter(function (t) { return t.length >= SEARCH_MIN_CHARS; });
      if (!parts.length) return value;
      var re = new RegExp('(' + parts.map(function (t) {
        return t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      }).join('|') + ')', 'ig');
      return value.replace(re, '<mark>$1</mark>');
    },

    popular: function () {
      var items = [];
      if (this.trending && Array.isArray(this.trending.trending)) {
        this.trending.trending.slice(0, 6).forEach(function (t) {
          items.push({ label: t.name, slug: t.slug });
        });
      }
      if (!items.length) {
        this.docs.slice(0, 6).forEach(function (d) {
          items.push({ label: d.name, slug: d.slug });
        });
      }
      return items;
    },

    topCategories: function (limit) {
      var counts = {};
      this.docs.forEach(function (d) {
        var c = d.category || 'other';
        counts[c] = (counts[c] || 0) + 1;
      });
      return Object.keys(counts)
        .sort(function (a, b) { return counts[b] - counts[a]; })
        .slice(0, limit || 5);
    }
  };
  OS.Search = Search;

  /* ============================================================================
     Catalog loader
     ----------------------------------------------------------------------------
     Pages that need the discovery catalog (the /collections/ and /favorites/
     views) all read the same API document, but only the flat/API URL families
     are guaranteed to exist in a deployed site — a preview served straight from
     the sources has just feeds/. Resolve the document from every published
     location, in order, so those pages can never be left empty by a missing
     copy: /api/catalog.json → /feeds/discovery.json → /discovery.json.
     ========================================================================== */
  var CATALOG_SOURCES = ['api/catalog.json', 'feeds/discovery.json', 'discovery.json'];

  OS.loadCatalog = function (timeoutMs) {
    var chain = Promise.resolve(null);
    CATALOG_SOURCES.forEach(function (path) {
      chain = chain.then(function (doc) {
        if (doc && Array.isArray(doc.apps)) return doc;
        return OS.fetchJSON(path, timeoutMs || 6000);
      });
    });
    return chain.then(function (doc) {
      var apps = doc && Array.isArray(doc.apps) ? doc.apps : [];
      if (apps.length) window.OS_CATALOG = apps;
      return apps;
    });
  };

  /* ============================================================================
     Global search palette (⌘K / Ctrl+K / "/")
     ----------------------------------------------------------------------------
     Injected once into <body>. Instant results with keyboard navigation,
     search history (localStorage) and popular searches while empty.
     ========================================================================== */
  var HISTORY_KEY = 'omnisource-search-history';
  var HISTORY_MAX = 8;

  var Palette = {
    el: null,
    input: null,
    body: null,
    isOpen: false,
    selected: 0,
    rows: [],          // visible, in DOM order: {type:'app'|'history', slug, name, q}
    lastFocus: null,

    build: function () {
      if (this.el) return;
      var el = document.createElement('div');
      el.className = 'os-palette';
      el.setAttribute('role', 'dialog');
      el.setAttribute('aria-modal', 'true');
      el.setAttribute('aria-label', 'Search OmniSource');
      el.innerHTML =
        '<div class="os-palette-backdrop" data-palette-close></div>' +
        '<div class="os-palette-panel">' +
          '<form class="os-palette-form" role="search">' +
            '<svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="11" cy="11" r="7" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="m20 20-4-4" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>' +
            '<input class="os-palette-input" type="search" placeholder="Search apps, bundle IDs, developers, categories…" ' +
            'autocomplete="off" spellcheck="false" aria-label="Search OmniSource" aria-expanded="false">' +
            '<kbd>esc</kbd>' +
          '</form>' +
          '<div class="os-palette-body" role="listbox" aria-label="Search results"></div>' +
          '<div class="os-palette-hints" aria-hidden="true">' +
            '<span><kbd>↑</kbd><kbd>↓</kbd> navigate</span>' +
            '<span><kbd>↵</kbd> open</span>' +
            '<span><kbd>esc</kbd> close</span>' +
          '</div>' +
        '</div>';
      document.body.appendChild(el);
      this.el = el;
      this.input = el.querySelector('.os-palette-input');
      this.body = el.querySelector('.os-palette-body');

      el.addEventListener('mousedown', function (event) {
        if (event.target.closest('[data-palette-close]')) Palette.close();
      });
      el.querySelector('form').addEventListener('submit', function (event) {
        event.preventDefault();
        Palette.activateSelected();
      });
      this.input.addEventListener('input', function () { Palette.render(this.value); });
      this.input.addEventListener('keydown', function (event) {
        if (event.key === 'ArrowDown') {
          event.preventDefault();
          Palette.selected = Math.min(Palette.rows.length - 1, Palette.selected + 1);
          Palette.paintSelection();
        } else if (event.key === 'ArrowUp') {
          event.preventDefault();
          Palette.selected = Math.max(0, Palette.selected - 1);
          Palette.paintSelection();
        } else if (event.key === 'Enter') {
          event.preventDefault();
          Palette.activateSelected();
        } else if (event.key === 'Escape') {
          Palette.close();
        }
      });
    },

    open: function () {
      this.build();
      if (this.isOpen) { this.input.focus(); return; }
      this.lastFocus = document.activeElement;
      this.isOpen = true;
      if (OS.closeNav) OS.closeNav();
      document.body.style.overflow = 'hidden';
      this.el.classList.add('is-open');
      this.input.value = '';
      this.selected = 0;
      this.render('');
      var self = this;
      // Focus after the entrance animation so it is visible.
      requestAnimationFrame(function () { self.input.focus(); });
      Search.load();
    },

    close: function () {
      if (!this.isOpen) return;
      this.isOpen = false;
      this.el.classList.remove('is-open');
      document.body.style.overflow = '';
      if (this.lastFocus && this.lastFocus.focus) this.lastFocus.focus();
    },

    /* -- history ----------------------------------------------------------- */
    history: function () {
      try {
        var list = JSON.parse(localStorage.getItem(HISTORY_KEY) || '[]');
        return Array.isArray(list) ? list : [];
      } catch (e) { return []; }
    },

    remember: function (entry) {
      try {
        var list = this.history().filter(function (item) {
          return !(item.q === entry.q && item.slug === entry.slug);
        });
        list.unshift(entry);
        localStorage.setItem(HISTORY_KEY, JSON.stringify(list.slice(0, HISTORY_MAX)));
      } catch (e) { /* private mode */ }
    },

    clearHistory: function () {
      try { localStorage.removeItem(HISTORY_KEY); } catch (e) { /* ignore */ }
      this.render(this.input.value);
    },

    /* -- rendering ---------------------------------------------------------- */
    appRow: function (doc, query, index) {
      var name = OS.Search.highlight(doc.name || '', query);
      var sub = OS.Search.highlight(doc.developer || doc.subtitle || '', query);
      var icon = asset(doc.icon || 'OmniSource.png');
      return '<a class="os-palette-row" href="' + OS.esc(url('apps/' + (doc.slug || doc.id) + '/')) + '" ' +
        'data-index="' + index + '" aria-selected="false" role="option">' +
        '<img src="' + OS.esc(icon) + '" alt="" width="38" height="38" loading="lazy">' +
        '<span class="info"><b>' + name + '</b><span>' + sub + '</span></span>' +
        '<span class="meta">' + OS.esc(String(doc.bundleId || '').slice(0, 30)) + '</span>' +
        '</a>';
    },

    historyRow: function (item, index) {
      return '<button class="os-palette-row" type="button" data-index="' + index + '" ' +
        'data-history="' + OS.esc(item.q) + '" aria-selected="false" role="option">' +
        '<svg viewBox="0 0 24 24" width="38" height="38" style="flex:none" aria-hidden="true">' +
        '<circle cx="12" cy="12" r="9" fill="none" stroke="var(--faint)" stroke-width="1.4"/>' +
        '<path d="M12 7v5l3.2 2" fill="none" stroke="var(--faint)" stroke-width="1.4" stroke-linecap="round"/></svg>' +
        '<span class="info"><b>' + OS.esc(item.q) + '</b><span>recent search</span></span>' +
        '<span class="meta">' + (item.name ? OS.esc(item.name) : '') + '</span>' +
        '</button>';
    },

    render: function (query) {
      if (!this.body) return;
      var q = String(query || '').trim();

      if (q.length < SEARCH_MIN_CHARS) {
        this.renderEmptyState();
        return;
      }

      Search.load().then(function () {
        if (!Palette.isOpen) return;
        var results = Search.search(q);
        if (!results.length) {
          Palette.body.innerHTML = '<div class="os-palette-empty">No matches for “' +
            OS.esc(q) + '”. Try a name, bundle ID, developer or tag.</div>';
          Palette.rows = [];
          return;
        }
        var html = '<div class="os-palette-group"><h4 class="os-palette-heading">Apps</h4>' +
          results.map(function (item, i) { return Palette.appRow(item.doc, q, i); }).join('') +
          '</div>';
        Palette.body.innerHTML = html;
        Palette.rows = results.map(function (item) {
          return { type: 'app', slug: item.doc.slug || item.doc.id, name: item.doc.name, q: q };
        });
        Palette.selected = 0;
        Palette.paintSelection();
      });
    },

    renderEmptyState: function () {
      var history = this.history();
      var popular = Search.popular();
      var categories = Search.topCategories(5);
      var html = '';

      if (history.length) {
        html += '<div class="os-palette-group"><h4 class="os-palette-heading">Recent ' +
          '<button type="button" data-clear-history>Clear</button></h4>' +
          history.map(function (item, i) { return this.historyRow(item, i); }, this).join('') +
          '</div>';
      }

      if (popular.length) {
        html += '<div class="os-palette-group"><h4 class="os-palette-heading">Popular</h4>' +
          '<div class="os-palette-chips">' + popular.map(function (p) {
            return '<button type="button" class="os-palette-chip" data-chip="' + OS.esc(p.label) + '">' +
              OS.esc(p.label) + '</button>';
          }).join('') + '</div></div>';
      }

      if (categories.length) {
        html += '<div class="os-palette-group"><h4 class="os-palette-heading">Categories</h4>' +
          '<div class="os-palette-chips">' + categories.map(function (c) {
            return '<button type="button" class="os-palette-chip" data-chip="' + OS.esc(c) + '">' +
              OS.esc(c.charAt(0).toUpperCase() + c.slice(1)) + '</button>';
          }).join('') + '</div></div>';
      }

      if (!html) {
        html = '<div class="os-palette-empty">Search apps by name, bundle ID, developer, source, category or tag.</div>';
      }
      this.body.innerHTML = html;
      this.rows = history.map(function (item) {
        return { type: 'history', q: item.q, slug: item.slug || '', name: item.name || '' };
      });
      this.selected = 0;
      this.paintSelection();
    },

    paintSelection: function () {
      $$('[data-index]', this.body).forEach(function (row) {
        row.setAttribute('aria-selected', String(Number(row.dataset.index) === Palette.selected));
      });
      var selectedRow = this.body.querySelector('[aria-selected="true"]');
      if (selectedRow && selectedRow.scrollIntoView) {
        selectedRow.scrollIntoView({ block: 'nearest' });
      }
    },

    activateSelected: function () {
      var row = this.rows[this.selected];
      if (!row) return;
      if (row.type === 'history') {
        this.input.value = row.q;
        this.render(row.q);
        return;
      }
      this.remember({ q: this.input.value.trim() || row.name, slug: row.slug, name: row.name, ts: Date.now() });
      this.close();
      location.href = url('apps/' + row.slug + '/');
    }
  };
  OS.Palette = Palette;

  /* -- palette global events (chips, history clear, row clicks) ------------- */
  document.addEventListener('click', function (event) {
    var chip = event.target.closest ? event.target.closest('[data-chip]') : null;
    if (chip && Palette.el && chip.closest('.os-palette')) {
      Palette.input.value = chip.dataset.chip || '';
      Palette.render(chip.dataset.chip);
      Palette.input.focus();
      return;
    }
    if (event.target.closest && event.target.closest('[data-clear-history]') && Palette.el) {
      Palette.clearHistory();
      return;
    }
    var historyBtn = event.target.closest ? event.target.closest('[data-history]') : null;
    if (historyBtn && Palette.el && historyBtn.closest('.os-palette')) {
      Palette.input.value = historyBtn.dataset.history || '';
      Palette.render(historyBtn.dataset.history);
      Palette.input.focus();
    }
  });

  document.addEventListener('keydown', function (event) {
    var tag = (event.target.tagName || '').toLowerCase();
    var typing = tag === 'input' || tag === 'textarea' || tag === 'select' || event.target.isContentEditable;
    if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') {
      event.preventDefault();
      Palette.isOpen ? Palette.close() : Palette.open();
    } else if (event.key === '/' && !typing && !Palette.isOpen) {
      event.preventDefault();
      Palette.open();
    } else if (event.key === 'Escape' && Palette.isOpen) {
      Palette.close();
    }
  });

  /* -- palette mount points: nav search button + hero search bar ------------- */
  document.addEventListener('click', function (event) {
    var opener = event.target.closest
      ? event.target.closest('[data-open-palette]')
      : null;
    if (opener) {
      event.preventDefault();
      Palette.open();
    }
  });

  /* --------------------------------------------------------------------- PWA */
  function registerServiceWorker() {
    if (!('serviceWorker' in navigator)) return;
    var host = location.hostname.toLowerCase();
    var isSecure = location.protocol === 'https:' || host === 'localhost' || host === '127.0.0.1';
    if (!isSecure) return;
    window.addEventListener('load', function () {
      navigator.serviceWorker.register(url('sw.js'))
        .then(function (reg) {
          if (reg.waiting) promptUpdate(reg.waiting);
          reg.addEventListener('updatefound', function () {
            var next = reg.installing;
            if (!next) return;
            next.addEventListener('statechange', function () {
              if (next.state === 'installed' && navigator.serviceWorker.controller) {
                promptUpdate(next);
              }
            });
          });
          navigator.serviceWorker.addEventListener('message', function (event) {
            if (event.data && event.data.type === 'omnisource-sw-updated') {
              OS.toast('A new version is ready. Reloading…');
              setTimeout(function () { location.reload(); }, 1200);
            }
          });
        })
        .catch(function () { /* offline support is progressive */ });
    });
  }

  function promptUpdate(worker) {
    // The page already has the new version available: ask the new worker to
    // take over; the SW posts an update message that reloads the page.
    try { worker.postMessage({ type: 'omnisource-skip-waiting' }); } catch (e) { /* ignore */ }
  }

  /* Generic QR dialog (static app pages).
     Pages carrying #qrButton[data-qr-feed] + #qrDialog get a working QR
     dialog with zero inline script. Home/install wire their own richer
     dialogs in js/site.js (different button ids), so this never conflicts. */
  function setupQrButton() {
    var button = $('#qrButton');
    var dialog = $('#qrDialog');
    if (!button || !dialog || !button.dataset.qrFeed) return;
    if (button._omniQrBound) return;
    button._omniQrBound = true;
    dialog.addEventListener('click', function (event) {
      if (event.target === dialog || (event.target.closest && event.target.closest('[data-close]'))) dialog.close();
    });
    button.addEventListener('click', function () {
      var img = $('#qrImage');
      if (img) {
        img.src = 'https://api.qrserver.com/v1/create-qr-code/?size=460x460&margin=0&data=' +
          encodeURIComponent(button.dataset.qrFeed);
      }
      if (!dialog.open) dialog.showModal();
    });
  }

  /* Header glass solidifies once the page scrolls (see .is-scrolled). */
  function setupHeaderState() {
    var header = $('.site-header') || $('.ap-header');
    if (!header) return;
    var ticking = false;
    var update = function () {
      ticking = false;
      header.classList.toggle('is-scrolled', window.scrollY > 8);
    };
    window.addEventListener('scroll', function () {
      if (!ticking) { ticking = true; requestAnimationFrame(update); }
    }, { passive: true });
    update();
  }

  /* Mobile glass drawer. Injected so generated app pages get it for free. */
  function setupMobileNav() {
    var nav = $('.site-header .nav') || $('.ap-header-inner');
    if (!nav) return;
    var links = nav.querySelector('.nav-links');
    if (!links) return;
    if (!links.id) links.id = 'navLinks';

    var btn = $('#navToggle');
    if (!btn) {
      btn = document.createElement('button');
      btn.id = 'navToggle';
      btn.className = 'icon-button nav-toggle';
      btn.type = 'button';
      btn.setAttribute('aria-label', 'Open menu');
      btn.setAttribute('aria-expanded', 'false');
      btn.setAttribute('aria-controls', links.id);
      btn.innerHTML =
        '<svg class="icon-menu" aria-hidden="true" viewBox="0 0 24 24"><path d="M4 7h16M4 12h16M4 17h16"/></svg>' +
        '<svg class="icon-close" aria-hidden="true" viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>';
      nav.appendChild(btn);
    }

    var backdrop = $('.nav-backdrop');
    if (!backdrop) {
      backdrop = document.createElement('div');
      backdrop.className = 'nav-backdrop';
      backdrop.setAttribute('aria-hidden', 'true');
      document.body.appendChild(backdrop);
    }

    // The "More" dropdown lives inside the same .nav-links container: in the
    // phone drawer its items must always be visible (CSS hides the summary),
    // while on desktop it behaves as a hover/click menu.
    var moreMenus = $$('.nav-more', links);
    function closeNav() {
      document.body.classList.remove('nav-open');
      btn.setAttribute('aria-expanded', 'false');
      btn.setAttribute('aria-label', 'Open menu');
      if (window.innerWidth > 1100) moreMenus.forEach(function (d) { d.open = false; });
    }
    function openNav() {
      document.body.classList.add('nav-open');
      btn.setAttribute('aria-expanded', 'true');
      btn.setAttribute('aria-label', 'Close menu');
      if (window.innerWidth <= 1100) moreMenus.forEach(function (d) { d.open = true; });
    }
    btn.addEventListener('click', function () {
      document.body.classList.contains('nav-open') ? closeNav() : openNav();
    });
    backdrop.addEventListener('click', closeNav);
    links.addEventListener('click', function (event) {
      if (event.target.closest && event.target.closest('a')) closeNav();
    });
    // Desktop: close the "More" menu when clicking/tapping outside of it.
    document.addEventListener('click', function (event) {
      if (window.innerWidth <= 1100) return;
      moreMenus.forEach(function (details) {
        if (details.open && !details.contains(event.target)) details.open = false;
      });
    });
    document.addEventListener('keydown', function (event) {
      if (event.key === 'Escape') moreMenus.forEach(function (d) { d.open = false; });
    });
    document.addEventListener('keydown', function (event) {
      if (event.key === 'Escape') closeNav();
    });
    window.addEventListener('resize', function () {
      if (window.innerWidth > 1100) closeNav();
    });
    OS.closeNav = closeNav;
  }

  /* Install prompt (beforeinstallprompt) — the browser hands us the moment. */
  var installEvent = null;
  window.addEventListener('beforeinstallprompt', function (event) {
    event.preventDefault();
    installEvent = event;
    var btn = document.querySelector('.install-prompt');
    if (btn) {
      btn.classList.add('is-visible');
      btn.addEventListener('click', function () {
        installEvent.prompt();
        installEvent.userChoice.then(function (choice) {
          if (choice.outcome === 'accepted') OS.toast('OmniSource installed');
          btn.classList.remove('is-visible');
          installEvent = null;
        });
      });
    }
  });

  /* ============================================================================
     Motion: scroll reveal + count-up (respecting prefers-reduced-motion).
     ========================================================================== */
  function setupReveal() {
    var nodes = $$('[data-reveal]');
    if (!nodes.length) return;
    if (OS.reducedMotion || !('IntersectionObserver' in window)) {
      nodes.forEach(function (n) { n.classList.add('is-revealed'); });
      return;
    }
    var observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          entry.target.classList.add('is-revealed');
          observer.unobserve(entry.target);
        }
      });
    }, { rootMargin: '0px 0px -36px 0px', threshold: 0.08 });
    nodes.forEach(function (n) { observer.observe(n); });
  }

  function animateCount(node, force) {
    if (node._omniCounting || (node._omniCounted && !force)) return;
    var raw = node.dataset.countValue != null ? String(node.dataset.countValue) : String(node.textContent);
    if (raw === '') return;
    // Non-numeric targets (e.g. "22/22") are rendered directly, no animation.
    if (!/^\d+(\.\d+)?$/.test(raw)) {
      node.textContent = raw;
      node.classList.add('os-count-done');
      node._omniCounted = true;
      return;
    }
    var target = parseFloat(raw);
    var suffix = node.dataset.countSuffix || '';
    var decimals = (raw.split('.')[1] || '').length;
    node._omniCounted = true;
    node._omniCounting = true;
    function finish() {
      node.textContent = target.toFixed(decimals) + suffix;
      node.classList.add('os-count-done');
      node._omniCounting = false;
    }
    if (OS.reducedMotion) {
      finish();
      return;
    }
    var start = null;
    var duration = 900;
    // Safety net: renderers whose requestAnimationFrame callbacks never fire
    // (headless capture, heavily throttled background tabs) would otherwise
    // sit at the starting number forever — land on the final value instead.
    var fallback = setTimeout(function () {
      if (node._omniCounting) finish();
    }, duration + 400);
    function frame(ts) {
      if (!node._omniCounting) return;
      if (start === null) start = ts;
      var p = Math.min(1, (ts - start) / duration);
      var eased = 1 - Math.pow(1 - p, 3);
      node.textContent = (target * eased).toFixed(decimals) + suffix;
      if (p < 1) {
        requestAnimationFrame(frame);
      } else {
        clearTimeout(fallback);
        finish();
      }
    }
    requestAnimationFrame(frame);
  }

  // Values for [data-count] nodes are set by page renderers *after* async
  // data loads, so arm a retry that animates as soon as a value appears
  // (and gives up after ~10 s, rendering whatever is there).
  function armCount(node, onDone) {
    if (node.dataset.countValue != null) {
      animateCount(node);
      if (onDone) onDone();
      return;
    }
    var tries = 0;
    (function tick() {
      if (!node.isConnected) return;
      if (node.dataset.countValue != null) {
        animateCount(node);
        if (onDone) onDone();
        return;
      }
      if (++tries > 50) {
        animateCount(node, true);
        return;
      }
      setTimeout(tick, 200);
    })();
  }

  function setupCounts() {
    var nodes = $$('[data-count]');
    if (!nodes.length) return;
    if (OS.reducedMotion || !('IntersectionObserver' in window)) {
      nodes.forEach(function (n) {
        n.classList.add('os-count');
        armCount(n);
      });
      return;
    }
    var observer = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (!entry.isIntersecting) return;
        var node = entry.target;
        if (node.dataset.countValue != null) {
          animateCount(node);
          observer.unobserve(node);
        } else {
          armCount(node, function () { observer.unobserve(node); });
        }
      });
    }, { threshold: 0.4 });
    nodes.forEach(function (n) {
      n.classList.add('os-count');
      observer.observe(n);
    });
  }

  /* ------------------------------------------------------------------ boot */
  function boot() {
    // Theme (also applied pre-paint by the inline bootstrap in <head>).
    var stored = 'auto';
    try { stored = localStorage.getItem('omnisource-theme') || 'auto'; } catch (e) { /* ignore */ }
    setTheme(THEMES.indexOf(stored) !== -1 ? stored : 'auto');

    // Theme + view toggles.
    var themeButton = $('#themeButton');
    if (themeButton) themeButton.addEventListener('click', cycleTheme);
    var viewToggle = $('#viewToggle');
    if (viewToggle) {
      viewToggle.addEventListener('click', function () {
        var compact = document.documentElement.dataset.view === 'compact';
        document.documentElement.dataset.view = compact ? 'grid' : 'compact';
        try { localStorage.setItem('omnisource-view', compact ? 'grid' : 'compact'); } catch (e) { /* ignore */ }
        viewToggle.setAttribute('aria-pressed', String(!compact));
        viewToggle.setAttribute('aria-label', compact ? 'Use compact view' : 'Use grid view');
        viewToggle.title = compact ? 'Compact view' : 'Grid view';
      });
    }

    // Footer year.
    var year = $('#year');
    if (year) year.textContent = String(new Date().getFullYear());

    setupQrButton();
    setupHeaderState();
    setupMobileNav();
    setupReveal();
    setupCounts();
    registerServiceWorker();
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot);
  } else {
    boot();
  }
})();
