"""Translation coverage document (``feeds/translation-status.json``).

Per-locale coverage against the canonical English locale (``locales/en.json``)
is a pure function of the committed locale files, so it is generated by the
build like every other ``feeds/`` document and mirrored to the API surface
(``api/translation-status.json``) by the repository-root publisher. It is
never written as a CI side effect: the validator
(``scripts/validate-translations.js``) recomputes the same report and fails
when the committed document drifts from the locale state.

The computation deliberately mirrors the validator's semantics so both
engines agree byte-for-byte on the same inputs:

* nested plain objects flatten to dotted keys, arrays and scalars are leaves;
* a canonical key is covered iff the locale object has it (empty values are
  a validator error, not a coverage deduction);
* the percentage rounds with JavaScript's ``Math.round`` (half up), not
  Python's banker's rounding, which would disagree on ``.5`` boundaries.
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

#: Locale file that acts as the source of truth for coverage.
CANONICAL_LOCALE = "en"


def flatten_locale(data: dict[str, Any], prefix: str = "") -> dict[str, Any]:
    """Flatten nested plain objects into dotted keys.

    Mirrors ``flat()`` in ``scripts/validate-translations.js``: a nested
    dictionary recurses under ``"parent.child"``; every other value
    (lists, strings, numbers, booleans, null) is a leaf at that key.
    """
    flat: dict[str, Any] = {}
    for key, value in data.items():
        path = f"{prefix}.{key}" if prefix else str(key)
        if isinstance(value, dict):
            flat.update(flatten_locale(value, path))
        else:
            flat[path] = value
    return flat


def js_round(value: float) -> int:
    """JavaScript's ``Math.round`` for non-negative values (half up)."""
    return math.floor(value + 0.5)


def build_translation_status_doc(locales_dir: Path) -> dict[str, int]:
    """Compute per-locale coverage percentages against ``locales/en.json``.

    Returns a mapping of locale name (file stem) to coverage percentage,
    with keys in sorted order so the serialized document is deterministic.
    Raises :class:`ValueError` when the locale state cannot produce a
    meaningful report (missing directory, missing or empty canonical
    locale, or a locale file that is not a JSON object).
    """
    if not locales_dir.is_dir():
        raise ValueError(f"locales directory not found: {locales_dir}")
    by_name: dict[str, Path] = {}
    for path in sorted(locales_dir.glob("*.json")):
        by_name[path.stem] = path
    if CANONICAL_LOCALE not in by_name:
        raise ValueError(f"locales/{CANONICAL_LOCALE}.json is required as the canonical source of truth")
    english = flatten_locale(_load_locale(by_name[CANONICAL_LOCALE]))
    if not english:
        raise ValueError(f"locales/{CANONICAL_LOCALE}.json has no keys; coverage is undefined")
    report: dict[str, int] = {}
    for name in sorted(by_name):
        data = flatten_locale(_load_locale(by_name[name]))
        missing = [key for key in english if key not in data]
        report[name] = js_round((len(english) - len(missing)) / len(english) * 100)
    return report


def _load_locale(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"{path.name}: unreadable locale file ({exc})") from exc
    if not isinstance(data, dict):
        raise ValueError(f"{path.name}: top level must be a JSON object")
    return data
