"""Tests for the translation-coverage artifact (``api/translation-status.json``).

The document must be generated by the offline build itself (not only by
``scripts/validate-translations.js``): the ``translation-status/`` page fetches
it, the API mirror prunes anything it does not publish, and
``check_reproducible.py`` fails when a committed artifact has no generator.
"""

from __future__ import annotations

import json
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
_SRC = ROOT / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from omnisource.site import _prune_mirror, _publish_api_mirror, _translation_status_document


class TestTranslationStatus(unittest.TestCase):
    def _write_locale(self, locales: Path, name: str, payload: dict) -> None:
        (locales / name).write_text(json.dumps(payload), encoding="utf-8")

    def test_coverage_math_matches_the_js_validator(self) -> None:
        # en defines 8 canonical keys; de misses 1 (7/8 = 87.5% -> Math.round
        # gives 88, Python's round() would give 88 only by luck — the build
        # uses floor(x + 0.5) to match Math.round exactly). xx is empty (0%),
        # fr misses 3 (5/8 = 62.5% -> 63).
        tmp = Path(tempfile.mkdtemp(prefix="omnisource-i18n-test-"))
        try:
            locales = tmp / "locales"
            locales.mkdir()
            en = {"a": "1", "b": {"c": "2"}, "d": "3", "e": "4", "f": "5", "g": "6", "h": "7", "i": "8"}
            self._write_locale(locales, "en.json", en)
            self._write_locale(locales, "de.json", {k: v for k, v in en.items() if k != "i"})
            self._write_locale(locales, "fr.json", {k: v for k, v in en.items() if k not in {"g", "h", "i"}})
            self._write_locale(locales, "xx.json", {})

            report = _translation_status_document(tmp)
            self.assertEqual(report, {"de": 88, "en": 100, "fr": 63, "xx": 0})
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def test_nested_and_leaf_values_count_like_the_js_flatten(self) -> None:
        # Nested maps flatten to dotted keys; arrays and null are leaf values
        # (the JS validator only recurses into plain objects).
        tmp = Path(tempfile.mkdtemp(prefix="omnisource-i18n-test-"))
        try:
            locales = tmp / "locales"
            locales.mkdir()
            self._write_locale(locales, "en.json", {"a": {"b": "x"}, "list": [1, 2], "n": None})
            self._write_locale(locales, "de.json", {"a": {"b": "y"}, "list": [1], "n": ""})

            report = _translation_status_document(tmp)
            self.assertEqual(report, {"de": 100, "en": 100})
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def test_no_locales_means_no_document(self) -> None:
        tmp = Path(tempfile.mkdtemp(prefix="omnisource-i18n-test-"))
        try:
            self.assertIsNone(_translation_status_document(tmp))
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def test_api_mirror_publishes_and_keeps_the_document(self) -> None:
        # The mirror must own the file (gzip twin included) so the pruning
        # pass never removes it again — that regression is what broke the
        # published page and failed the reproducibility check.
        tmp = Path(tempfile.mkdtemp(prefix="omnisource-i18n-test-"))
        try:
            published = _publish_api_mirror(ROOT, tmp, brotli=False)
            self.assertIn("translation-status.json", published["published"])
            target = tmp / "translation-status.json"
            self.assertTrue(target.is_file())

            expected = _translation_status_document(ROOT)
            assert expected is not None
            self.assertEqual(
                target.read_text(encoding="utf-8"),
                json.dumps(expected, indent=2, sort_keys=True) + "\n",
                "published document diverged from the locales/ coverage",
            )
            self.assertTrue((tmp / "translation-status.json.gz").is_file(), "gzip twin missing")

            # The live locales are all at 100% today; a locale regressing is
            # fine (the number just drops), but the document must stay sorted
            # and deterministic.
            self.assertEqual(list(json.loads(target.read_text(encoding="utf-8"))), sorted(expected))
            # …and pruning with the mirror's own keep-set must keep it.
            self.assertEqual([p.name for p in _prune_mirror(tmp, set(published["published"]))], [])
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

    def test_committed_artifact_matches_the_build(self) -> None:
        # The copy committed under api/ must be exactly what a rebuild
        # produces, or check_reproducible.py fails the CI run.
        expected = _translation_status_document(ROOT)
        assert expected is not None
        committed = ROOT / "api" / "translation-status.json"
        self.assertTrue(
            committed.is_file(), "api/translation-status.json is missing: the translation-status page would 404"
        )
        self.assertEqual(
            committed.read_text(encoding="utf-8"),
            json.dumps(expected, indent=2, sort_keys=True) + "\n",
        )


if __name__ == "__main__":
    unittest.main()
