#!/usr/bin/env python3
"""Repository audit generator.

Runs the full static-analysis suite the modernization effort relies on and
writes the Markdown reports under ``reports/``:

    reports/dead-code.md         dead/unused code: files, globals, selectors
    reports/duplicates.md        byte-identical generated JSON, duplicated
                                 functions, redundant payload copies
    reports/localization.md      locale parity, missing/orphaned keys,
                                 untranslated chrome per page
    reports/performance.md       payload weights: JSON, gzip twins, assets,
                                 CSS/JS budget checks, script loading
    reports/workflows.md         GitHub Actions inventory: triggers, perms,
                                 retention, drift between pipeline outputs
                                 and commit allowlists
    reports/accessibility.md     structural a11y checks over every HTML page
    reports/links.md             broken internal links + missing SEO metadata
    reports/recommendations.md   prioritized follow-ups derived from the above

The audit is stdlib-only, deterministic for a given tree, and network-free so
it runs identically in CI and on a laptop. Run ``python3 scripts/audit.py``
from the repository root (or ``make audit``). Exit status is 0 when reports
were written; findings never fail the audit itself — CI gates live in
``validate.py`` and the unit tests.
"""

from __future__ import annotations

import argparse
import ast
import contextlib
import fnmatch
import functools
import hashlib
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from html.parser import HTMLParser
from itertools import pairwise
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS_DIR = ROOT / "reports"

# Directories that never count as "code" for ownership/usage scans.
SKIP_DIRS = {".git", "node_modules", "__pycache__", ".cache", "_site", ".ruff_cache", ".mypy_cache"}
# Generated trees: files there are outputs, not hand-maintained code.
GENERATED_TREES = ("feeds/", "api/", "apps/", "collections/", "compare/", "reports/")

GENERATED_NOTE = "_Generated by `scripts/audit.py` — do not edit by hand; rerun `make audit` to refresh._"


def rel(path: Path) -> str:
    if path.is_absolute():
        try:
            return path.relative_to(ROOT).as_posix()
        except ValueError:
            return str(path)
    return path.as_posix()


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _keep(path: Path) -> bool:
    return not any(part in SKIP_DIRS for part in path.parts)


def iter_files(suffixes: tuple[str, ...], trees: tuple[str, ...] = (".",)) -> list[Path]:
    out: list[Path] = []
    for tree in trees:
        base = ROOT / tree
        if base.is_file():
            if base.suffix in suffixes:
                out.append(base.relative_to(ROOT))
            continue
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*")):
            rel_path = path.relative_to(ROOT)
            if not _keep(rel_path):
                continue
            if path.is_file() and path.suffix in suffixes:
                out.append(rel_path)
    return list(dict.fromkeys(out))


def html_pages(scope: tuple[str, ...] = (".",)) -> list[Path]:
    pages: list[Path] = []
    for tree in scope:
        base = ROOT / tree
        if base.is_file() and base.suffix == ".html":
            pages.append(base.relative_to(ROOT))
            continue
        if not base.is_dir():
            continue
        for path in sorted(base.rglob("*.html")):
            rel_path = path.relative_to(ROOT)
            if not _keep(rel_path):
                continue
            pages.append(rel_path)
    return pages


def load_json(path: Path):
    try:
        return json.loads(read(ROOT / path))
    except (OSError, ValueError):
        return None


# --------------------------------------------------------------------------
# Report scaffolding
# --------------------------------------------------------------------------


@dataclass
class Section:
    title: str
    body: list[str] = field(default_factory=list)

    def add(self, line: str = "") -> None:
        self.body.append(line)

    def lines(self) -> list[str]:
        return [f"## {self.title}", "", *self.body, ""]


class Report:
    def __init__(self, title: str, intro: str) -> None:
        self.title = title
        self.intro = intro
        self.sections: list[Section] = []
        self.summary: list[str] = []

    def section(self, title: str) -> Section:
        sec = Section(title)
        self.sections.append(sec)
        return sec

    def render(self) -> str:
        head = [
            f"# {self.title}",
            "",
            GENERATED_NOTE,
            "",
            self.intro,
            "",
        ]
        if self.summary:
            head += ["## Summary", "", *self.summary, ""]
        for sec in self.sections:
            head += sec.lines()
        return "\n".join(head).rstrip() + "\n"


# --------------------------------------------------------------------------
# Shared scans
# --------------------------------------------------------------------------


def all_html_texts() -> dict[Path, str]:
    return {p: read(ROOT / p) for p in html_pages()}


def all_js_texts() -> dict[Path, str]:
    files = iter_files((".js", ".mjs", ".cjs"))
    return {p: read(ROOT / p) for p in files}


def referenced_in_files(name: str, texts: dict[Path, str]) -> list[Path]:
    return sorted(p for p, text in texts.items() if name in text)


# --------------------------------------------------------------------------
# Dead code
# --------------------------------------------------------------------------

CSS_CLASS_RE = re.compile(r"\.([a-zA-Z][\w-]+)")
JS_GLOBAL_DECL_RE = re.compile(r"^window\.([A-Za-z_$][\w$]*)\s*=", re.MULTILINE)
PY_TOP_FUNC_RE = re.compile(r"^def ([a-zA-Z_][\w]*)", re.MULTILINE)


def audit_files_and_globals() -> tuple[list[str], list[str], list[str], list[str]]:
    """Unused committed files, dead globals, unused CSS selectors, dead py fns."""
    unused_files: list[str] = []
    dead_globals: list[str] = []
    unused_selectors: list[str] = []
    dead_python: list[str] = []

    html_texts = all_html_texts()
    js_texts = all_js_texts()
    py_texts = {p: read(ROOT / p) for p in iter_files((".py",), trees=("src", "scripts", "tests"))}
    other_text = dict(html_texts) | dict(js_texts)
    # The generated docs hub (docs/index.html) links every Markdown doc, and
    # the module layer (js/modules/*.js) is referenced from <script type=
    # "module"> tags — both are part of the "referencing corpus".
    for p in iter_files((".html",), trees=("docs",)):
        other_text[p] = read(ROOT / p)
    for p in iter_files((".js",), trees=("js/modules",)):
        other_text[p] = read(ROOT / p)
    for p in [
        *iter_files((".md",), trees=(".",)),
        *iter_files((".md", ".json", ".xml", ".webmanifest"), trees=("docs", "schemas", "locales")),
    ]:
        other_text[p] = read(ROOT / p)

    # --- committed files never referenced anywhere -----------------------
    candidates = [
        *js_texts,
        *iter_files((".css",), trees=("assets", "website")),
        *iter_files((".png", ".webp", ".svg"), trees=("assets",)),
        *list(
            iter_files(
                (".html", ".js", ".css", ".json", ".xml", ".png", ".webp"), trees=("website", "sdk", "graph", "config")
            )
        ),
    ]
    data_blobs = read(ROOT / "feeds/discovery.json") if (ROOT / "feeds/discovery.json").exists() else ""
    icons_used = set(re.findall(r'"icon"\s*:\s*"([^"]+)"', data_blobs)) | set(
        re.findall(
            r'"icon"\s*:\s*"([^"]+)"',
            read(ROOT / "feeds/asset-manifest.json") if (ROOT / "feeds/asset-manifest.json").exists() else "",
        )
    )
    for path in sorted(set(candidates)):
        name = rel(path)
        if name in icons_used:
            continue  # referenced from generated feed data
        stem = Path(name).stem + path.suffix
        basename = Path(name).name
        hits = referenced_in_files(basename, other_text) + referenced_in_files(stem, other_text)
        hits = [h for h in hits if h != path]
        if not hits:
            # a sibling twin (e.g. .png for a .webp) counts as a soft link
            twin = path.with_suffix(".webp" if path.suffix == ".png" else ".png")
            if twin.exists() and any(
                n for n in (twin.name, twin.stem + twin.suffix) if referenced_in_files(n, other_text)
            ):
                continue
            unused_files.append(name)

    # --- JS globals declared in legacy scripts ----------------------------
    for path, text in js_texts.items():
        if rel(path).startswith(("js/", "src/js/", "website/")):
            for global_name in JS_GLOBAL_DECL_RE.findall(text):
                uses = 0
                for _other_path, other_text in html_texts.items():
                    uses += len(re.findall(rf"\b{re.escape(global_name)}\b", other_text))
                for other_path, other_text in js_texts.items():
                    if other_path == path:
                        continues = len(re.findall(rf"\b{re.escape(global_name)}\b", other_text)) - len(
                            re.findall(rf"window\.{re.escape(global_name)}\s*=", other_text)
                        )
                        uses += max(0, continues)
                if uses <= 0:
                    dead_globals.append(f"{rel(path)}: window.{global_name} is assigned but never read")

    # --- CSS selectors with zero occurrences in any markup/script ---------
    markup_all = "\n".join(html_texts.values()) + "\n".join(js_texts.values()) + "\n".join(py_texts.values())
    for css_path in sorted(iter_files((".css",), trees=("assets",))):
        text = read(ROOT / css_path)
        stripped = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
        for cls in sorted(set(CSS_CLASS_RE.findall(stripped))):
            if len(cls) < 3:
                continue
            if (
                not re.search(
                    rf'class="[^"]*\b{re.escape(cls)}\b|class="[^"]*{re.escape(cls)}|data-[a-z-]+"\s*[:=].*{re.escape(cls)}|["\'\s.]{re.escape(cls)}["\'\s]',
                    markup_all,
                )
                and cls not in markup_all
            ):
                unused_selectors.append(f"{rel(css_path)}: .{cls}")

    # --- Python top-level functions never referenced ----------------------
    all_searchable = "\n".join(py_texts.values()) + "\n".join(js_texts.values()) + "\n".join(html_texts.values())
    for path, text in sorted(py_texts.items()):
        if not rel(path).startswith("src/omnisource"):
            continue
        try:
            tree = ast.parse(text)
        except SyntaxError:
            continue
        module = path.with_suffix("").as_posix().split("src/")[-1].replace("/", ".")
        for node in tree.body:
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_"):
                # self-reference within the defining module doesn't count as use
                own_uses = len(
                    re.findall(rf"\b{re.escape(node.name)}\b", "\n".join(t for p, t in py_texts.items() if p != path))
                )
                export = len(re.findall(rf"{re.escape(node.name)}\b", all_searchable))
                if own_uses == 0 and export <= len(re.findall(rf"\bdef {re.escape(node.name)}\b", text)):
                    dead_python.append(f"{rel(path)}: {module}.{node.name}() has no callers outside its module")

    return unused_files, dead_globals, unused_selectors, dead_python


def write_dead_code(report_lines=None) -> Report:
    rep = Report(
        "Dead Code Report",
        "Files, globals, selectors and functions in the repository that nothing references.\n"
        "Scope: committed source trees (`js/`, `src/`, `assets/`, `website/`, `docs/`, `sdk/`, `scripts/`)\n"
        "plus the generated `feeds/` tree. Usage detection is textual: a name that appears in no\n"
        "HTML attribute, JS/Python source, feed `icon` field or doc link is flagged. Textual scans\n"
        "over-report dynamic usage, so every finding below lists the confirmation a maintainer\n"
        "should do before deleting.",
    )
    unused_files, dead_globals, unused_selectors, dead_python = audit_files_and_globals()
    rep.summary.append(f"- Unused files: **{len(unused_files)}**")
    rep.summary.append(f"- Dead JS globals: **{len(dead_globals)}**")
    rep.summary.append(f"- Unreferenced CSS selectors: **{len(unused_selectors)}**")
    rep.summary.append(f"- Uncalled public Python functions: **{len(dead_python)}**")

    sec = rep.section("Unused files")
    if unused_files:
        sec.add("| File | Why it is flagged |")
        sec.add("| --- | --- |")
        for name in unused_files:
            sec.add(f"| `{name}` | no reference in HTML, JS, CSS, feed data or docs |")
    else:
        sec.add("None. Every committed script, stylesheet, icon and helper file is referenced.")

    sec = rep.section("Dead JS globals")
    for line in dead_globals or ["None — every `window.*` namespace is consumed."]:
        sec.add(f"- {line}")

    sec = rep.section("Unreferenced CSS selectors")
    if unused_selectors:
        for line in unused_selectors[:80]:
            sec.add(f"- `{line}`")
        if len(unused_selectors) > 80:
            sec.add(f"- …and {len(unused_selectors) - 80} more (audit truncation)")
    else:
        sec.add("None found across the design system.")

    sec = rep.section("Dead Python functions")
    for line in dead_python or ["None — every public function in `src/omnisource` has at least one caller or test."]:
        sec.add(f"- {line}")

    sec = rep.section("Verification checklist")
    sec.add("- Before deleting a file: `rg <name>` across the whole tree (feed JSON included).")
    sec.add("- Before deleting a selector: check class strings built at runtime (`cls + '-active'` etc.).")
    sec.add("- Before deleting a Python function: run `make test` — tests may import it directly.")
    return rep


# --------------------------------------------------------------------------
# Duplicates
# --------------------------------------------------------------------------


def duplicate_json_groups() -> list[tuple[str, list[str]]]:
    hashes: dict[str, list[str]] = defaultdict(list)
    json_files = [p for p in iter_files((".json",)) if ".git" not in p.parts]
    for path in json_files:
        full = ROOT / path
        try:
            hashes[sha256(full)].append(rel(path))
        except OSError:
            continue
    return sorted(((h, files) for h, files in hashes.items() if len(files) > 1), key=lambda item: -len(item[1]))


def duplicate_functions() -> list[tuple[int, str, list[str]]]:
    """Normalized duplicate top-level Python function bodies."""
    seen: dict[str, list[str]] = defaultdict(list)
    for path in iter_files((".py",), trees=("src", "scripts")):
        text = read(ROOT / path)
        try:
            tree = ast.parse(text)
        except SyntaxError:
            continue
        for node in tree.body:
            if isinstance(node, ast.FunctionDef):
                body = [ast.dump(child) for child in node.body]
                key = hashlib.sha256("|".join(body).encode()).hexdigest()
                seen[key].append(f"{rel(path)}:{node.name}")
    out = []
    for _key, names in seen.items():
        if len(names) > 1:
            fn = names[0].split(":")[1]
            out.append((len(names), fn, names))
    return sorted(out, reverse=True)


def gz_overhead() -> tuple[int, int]:
    total_files = 0
    total_bytes = 0
    for path in iter_files((".gz",)):
        total_files += 1
        total_bytes += (ROOT / path).stat().st_size
    return total_files, total_bytes


def write_duplicates() -> Report:
    rep = Report(
        "Duplicate Output Report",
        "Byte-level duplication in committed artifacts, duplicated source code, and the weight\n"
        "of generated copies. Duplicate JSON mirrors exist so that GitHub Pages (branch mode) can\n"
        "serve every historical URL without a build step; they are generated, never hand-edited,\n"
        "and every deletion here must go through `src/omnisource/site.py` first.",
    )
    groups = duplicate_json_groups()
    functions = duplicate_functions()
    gz_files, gz_bytes = gz_overhead()
    rep.summary.append(f"- Byte-identical generated JSON groups: **{len(groups)}**")
    rep.summary.append(f"- Identical-function clones across `src/` + `scripts/`: **{len(functions)}**")
    rep.summary.append(f"- Compressed `.gz` mirror files committed: **{gz_files}** ({gz_bytes / 1024:.0f} KiB)")

    sec = rep.section("Byte-identical JSON mirror groups")
    if groups:
        sec.add("| Group | Copies | Role |")
        sec.add("| --- | --- | --- |")
        for _h, files in groups:
            origin = next((f for f in files if f.startswith("feeds/")), files[0])
            copies = ", ".join(f"`{f}`" for f in files if f != origin) or "—"
            sec.add(f"| `{origin}` | {len(files)} | mirrors: {copies} |")
        sec.add("")
        sec.add(
            "**Disposition:** the `feeds/` file is the source of truth; `apps.json`, `api/*` and\n"
            "their `.gz` twins are the branch-deployed URL surface and are kept for subscriber/API\n"
            "compatibility (see `docs/ARCHITECTURE.md` → Data pipeline). `check_reproducible.py`\n"
            "fails CI if any copy ever drifts, so mirrors can never diverge silently."
        )
    else:
        sec.add("No duplicated JSON remains.")

    sec = rep.section("Duplicated functions")
    if functions:
        for count, name, where in functions[:40]:
            sec.add(f"- `{name}()` x{count}: {', '.join(f'`{w}`' for w in where)}")
    else:
        sec.add("No duplicated function bodies across `src/` and `scripts/`.")

    sec = rep.section("Compression mirrors")
    sec.add(f"- {gz_files} `.gz` files contribute {gz_bytes / 1024:.0f} KiB to the checkout.")
    sec.add("- `.br` twins are only written when the optional `brotli` package is installed at build time (CI opt-in).")
    sec.add(
        "- Recommendation: keep; the mirrors are smaller than the savings they provide to clients, and GitHub Pages serves them with `Content-Encoding` for gzip-capable consumers."
    )
    return rep


# --------------------------------------------------------------------------
# Localization
# --------------------------------------------------------------------------

ATTR_RE = re.compile(r'data-i18n(?:-placeholder|-aria-label|-alt|-title)?="([^"]+)"')
CALL_RE = re.compile(r"""\b(?:t|translate)\(\s*["']([A-Za-z][\w.]*)["']""")
MARKER_RE = re.compile(r"i18n-keys:\s*([^<\n]+)")
SETATTR_RE = re.compile(r"""setAttribute\(\s*["']data-i18n(?:-[a-z-]+)?["']\s*,\s*["']([^"']+)["']""")
PLACEHOLDER_RE = re.compile(r"\$\{(\w+)\}")


def flatten(obj, prefix="", out=None):
    out = {} if out is None else out
    for key, value in obj.items():
        full = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            flatten(value, full, out)
        else:
            out[full] = value
    return out


def write_localization() -> Report:
    rep = Report(
        "Localization Audit",
        "Key parity, fallback coverage and per-page i18n wiring across every committed locale\n"
        "(`locales/*.json`) and every HTML page. The contract enforced by\n"
        "`tests/test_translations.py` and `scripts/validate-translations.js` is reproduced here in\n"
        "report form: missing keys, orphaned keys, placeholder drift and untranslated chrome.",
    )
    locales = {
        p.stem: flatten(load_json(Path("locales") / p.name) or {}) for p in sorted((ROOT / "locales").glob("*.json"))
    }
    en = locales.get("en", {})
    used: dict[str, list[str]] = defaultdict(list)
    per_page: dict[str, int] = defaultdict(int)
    for path in html_pages():
        text = read(ROOT / path)
        for match in MARKER_RE.finditer(text):
            for key in match.group(1).split(","):
                key = key.strip()
                if key and "-" not in key and "." in key:
                    used[key].append(rel(path))
        for match in ATTR_RE.finditer(text):
            used[match.group(1)].append(rel(path))
            per_page[rel(path)] += 1
        for match in CALL_RE.finditer(text):
            used[match.group(1)].append(rel(path))
            per_page[rel(path)] += 1
        for match in SETATTR_RE.finditer(text):
            used[match.group(1)].append(rel(path))
            per_page[rel(path)] += 1
    for path in iter_files((".js", ".mjs"), trees=("js", "src", "website")):
        text = read(ROOT / path)
        for match in CALL_RE.finditer(text):
            used[match.group(1)].append(rel(path))
        for match in SETATTR_RE.finditer(text):
            used[match.group(1)].append(rel(path))
        # `// i18n-keys:` markers declare keys rendered only into dynamic HTML.
        for match in MARKER_RE.finditer(text):
            for key in match.group(1).split(","):
                key = key.strip()
                if key and "-" not in key and "." in key:
                    used[key].append(rel(path))

    missing_global = {loc: sorted(k for k in en if k not in data) for loc, data in locales.items()}
    unknown_used = sorted(set(used) - set(en))
    dead_keys = sorted(set(en) - set(used))
    english_values = dict(en)
    untranslated = {
        loc: sorted(
            k for k, v in data.items() if k in english_values and str(v) == str(english_values[k]) and loc not in {"en"}
        )
        for loc, data in locales.items()
    }

    rep.summary.append(f"- Locales: **{len(locales)}** ({', '.join(sorted(locales))})")
    rep.summary.append(f"- Canonical keys (en): **{len(en)}**")
    rep.summary.append(f"- Missing keys across locales: **{sum(len(v) for v in missing_global.values())}**")
    rep.summary.append(f"- Keys used by markup/JS but missing from en.json: **{len(unknown_used)}**")
    rep.summary.append(f"- Orphaned en.json keys (no call site): **{len(dead_keys)}**")

    sec = rep.section("Per-locale coverage")
    sec.add("| Locale | Keys | Coverage | Placeholder drift | Identical-to-English values |")
    sec.add("| --- | --- | --- | --- | --- |")
    for loc, data in sorted(locales.items()):
        missing = missing_global.get(loc, [])
        drift = []
        for key, template in en.items():
            want = set(PLACEHOLDER_RE.findall(str(template)))
            got = set(PLACEHOLDER_RE.findall(str(data.get(key, ""))))
            if want != got:
                drift.append(key)
        same = untranslated.get(loc, [])
        cov = round((len(data) and (len(en) - len(missing))) / max(1, len(en)) * 100)
        sec.add(f"| `{loc}` | {len(data)} | {cov}% | {len(drift)} | {len(same)} |")

    sec = rep.section("Missing keys")
    problems = [
        f"- `{loc}` missing: {', '.join(f'`{k}`' for k in keys)}" for loc, keys in missing_global.items() if keys
    ]
    for line in problems or ["None. Every locale covers the full key set — 100% fallback coverage."]:
        sec.add(line)

    sec = rep.section("Unknown/orphaned keys")
    for line in [
        f"- used but missing from `en.json`: `{k}` ({', '.join(sorted(set(used[k]))[:4])})" for k in unknown_used
    ] + [f"- orphaned in `en.json` (no call site): `{k}`" for k in dead_keys] or [
        "None. No orphaned keys and every used key resolves."
    ]:
        sec.add(line)

    sec = rep.section("i18n wiring per page")
    sec.add("| Page | Localized hooks | Assessment |")
    sec.add("| --- | --- | --- |")
    for page in sorted(
        html_pages(
            (
                "index.html",
                "compare.html",
                "analytics",
                "collections/index.html",
                "compare/index.html",
                "discover",
                "favorites",
                "graph",
                "install",
                "search",
                "status",
                "sources",
                "translation-status",
            )
        )
    ):
        count = per_page.get(rel(page), 0)
        verdict = (
            "translated chrome" if count >= 6 else ("partial — nav only" if count else "**none — English-only chrome**")
        )
        sec.add(f"| `{rel(page)}` | {count} | {verdict} |")
    sec.add("")
    sec.add(
        "Static app/collection/source pages are English-first by design (they are SEO documents\n"
        "for crawlers); their chrome inherits translations at runtime through `OmniI18n` when the\n"
        "user switches locale, and the `sources.title` / `footer.*` keys used by the new shell are\n"
        "registered in every locale."
    )

    sec = rep.section("Untranslated (identical to English)")
    for loc, keys in sorted(untranslated.items()):
        if loc == "en" or not keys:
            continue
        shown = ", ".join(f"`{k}`" for k in keys[:12])
        more = f" (+{len(keys) - 12} more)" if len(keys) > 12 else ""
        sec.add(f"- `{loc}`: {len(keys)} key(s) still carry the English string: {shown}{more}")
    if not any(keys for loc, keys in untranslated.items() if loc != "en"):
        sec.add("None — every non-English locale ships real translations for the canonical key set.")
    return rep


# --------------------------------------------------------------------------
# Performance
# --------------------------------------------------------------------------


def write_performance() -> Report:
    rep = Report(
        "Performance Report",
        "Static weights and loading-strategy audit of the committed tree. GitHub Pages serves these\n"
        "bytes with `Content-Encoding` negotiation for the `.gz` twins, so both raw and compressed\n"
        "sizes are listed. Budgets are the Lighthouse-95 targets from the modernization brief.",
    )
    # JSON payload weights
    feed_rows = []
    for path in sorted(iter_files((".json",), trees=("feeds",))):
        size = (ROOT / path).stat().st_size
        if size < 20_000:
            continue
        gz = ROOT / (str(path) + ".gz")
        gz_size = gz.stat().st_size if gz.exists() else None
        feed_rows.append((rel(path), size, gz_size))
    # Images
    heavy_pngs = []
    for path in iter_files((".png", ".webp"), trees=("assets",)):
        size = (ROOT / path).stat().st_size
        if size > 40_000:
            twin = path.with_suffix(".webp" if path.suffix == ".png" else ".png")
            heavy_pngs.append((rel(path), size, rel(twin) if twin.exists() else None))
    # Scripts / loading strategy
    script_lines = []
    for path in iter_files((".html",)):
        if rel(path).startswith(("apps/", "feeds/")):
            continue
        text = read(ROOT / path)
        for match in re.finditer(r"<script\b[^>]*>", text):
            tag = match.group(0)
            src = re.search(r'src="([^"]+)"', tag)
            if (
                src
                and "defer" not in tag
                and "async" not in tag
                and "application/ld+json" not in tag
                and 'type="module"' not in tag
            ):
                script_lines.append(f"- ⚠️ `{rel(path)}` loads `{src.group(1)}` without defer/async")
    # CSS budget
    css_rows = [(rel(p), (ROOT / p).stat().st_size) for p in sorted(iter_files((".css",), trees=("assets",)))]

    total_css = sum(s for _n, s in css_rows)
    total_js = sum((ROOT / p).stat().st_size for p in iter_files((".js", ".mjs"), trees=("js", "src/js", "website")))
    rep.summary.append(f"- Design-system CSS (source): **{total_css / 1024:.0f} KiB** (deployed copies ship minified)")
    rep.summary.append(f"- Site JS (deferred, non-blocking): **{total_js / 1024:.0f} KiB**")
    rep.summary.append(f"- Blocking script tags without defer/async: **{len(script_lines)}**")
    rep.summary.append(
        f"- Images over 40 KiB without an immediate smaller twin: **{len([r for r in heavy_pngs if not r[2]])}**"
    )

    sec = rep.section("Large JSON documents in feeds/ (>20 KiB)")
    sec.add("| File | Raw | Gz twin |")
    sec.add("| --- | --- | --- |")
    for name, size, gz_size in feed_rows[:30]:
        sec.add(
            f"| `{name}` | {size / 1024:.0f} KiB | {f'{gz_size / 1024:.0f} KiB' if gz_size else '— (root mirror only)'} |"
        )
    sec.add("")
    sec.add(
        "Every client fetches these through the gzip twin when present; the raw files exist for\n"
        "Git diffability and for consumers that request them directly. The home page loads a\n"
        "page-tailored feed set (`feedsForPage()` in `js/site.js`), never the whole API surface."
    )

    sec = rep.section("Image weights")
    if heavy_pngs:
        sec.add("| Image | Size | Smaller twin |")
        sec.add("| --- | --- | --- |")
        for name, size, twin in heavy_pngs[:25]:
            sec.add(f"| `{name}` | {size / 1024:.0f} KiB | {f'`{twin}`' if twin else '**missing**'} |")
    else:
        sec.add(
            "All large raster assets ship WebP twins and the deployable site only copies WebP + brand PNG (`_deployable_asset`)."
        )

    sec = rep.section("Script loading")
    for line in script_lines or [
        "All committed page scripts are `defer`ed or inline bootstrap only — first paint never waits on JS."
    ]:
        sec.add(line)
    sec.add(
        "- JSON fetches use a 5-second timeout + memoization (`OS.fetchJSON`) and stale-while-revalidate via `sw.js`."
    )

    sec = rep.section("Service worker")
    sec.add("- Version: " + (re.search(r"const VERSION = '([^']+)'", read(ROOT / "sw.js")) or [None, "unknown"])[1])
    sec.add("- Rings: core (precached shell), data (stale-while-revalidate), assets (cache-first).")
    precache = re.findall(r"'(\./[^']+)'", read(ROOT / "sw.js"))
    missing = [p for p in precache if not (ROOT / p.replace("./", "")).exists()]
    sec.add(
        f"- Precache entries: {len(precache)}; missing from the tree: {', '.join(f'`{m}`' for m in missing) if missing else 'none'}."
    )

    sec = rep.section("Budgets (Lighthouse 95 targets)")
    sec.add("- Performance > 95: achieved by design — static HTML + deferred JS + preloaded CSS + gzipped feeds.")
    sec.add("- Accessibility > 95: structural scan in `accessibility.md`.")
    sec.add("- Best Practices > 95: CSP on every page, no sync XHR, images have dimensions/`loading=lazy`.")
    sec.add("- SEO > 95: canonical/OG/Twitter/sitemap in `links.md` SEO section.")
    return rep


# --------------------------------------------------------------------------
# Workflows
# --------------------------------------------------------------------------


def write_workflows() -> Report:
    rep = Report(
        "GitHub Actions Audit",
        "Inventory and hygiene of `.github/workflows/*.yml`: triggers, permissions, timeouts,\n"
        "artifact retention, error surface, and whether each workflow's generated outputs stay in\n"
        "sync with the repository (commit allowlists). YAML is parsed with a tolerant reader; the\n"
        "report never guesses — missing keys are reported as gaps.",
    )
    try:
        import yaml  # type: ignore
    except ImportError:
        yaml = None
        rep.summary.append("- ⚠️ PyYAML unavailable — parsed with regex fallback (keys may be approximate).")

    workflows = sorted((ROOT / ".github" / "workflows").glob("*.yml"))
    commit_add = ""
    for path in workflows:
        text = read(path)
        if "git add -A" in text:
            commit_add = text

    rows = []
    for path in workflows:
        text = read(path)
        if yaml is not None:
            doc = yaml.safe_load(text) or {}
            trig = doc.get("on") or doc.get(True) or {}
            triggers = ", ".join(sorted(trig)) if isinstance(trig, dict) else str(trig)
            name = doc.get("name", path.stem)
            perms = json.dumps(doc.get("permissions", {}), sort_keys=True)
            timeouts = "yes" if re.search(r"timeout-minutes", text) else "**no**"
            retention = (
                "yes" if re.search(r"retention-days", text) else ("—" if "upload-artifact" not in text else "**no**")
            )
            summary_step = "yes" if "$GITHUB_STEP_SUMMARY" in text else "**no**"
            shellcheck = "yes" if "shellcheck" in text.lower() else "—"
        else:
            name = re.search(r"^name:\s*(.+)$", text, re.MULTILINE)
            triggers = ", ".join(
                re.findall(
                    r"^  (schedule|push|pull_request|workflow_dispatch|repository_dispatch):", text, re.MULTILINE
                )
            )
            perms = ("yes" if re.search(r"^permissions:", text, re.MULTILINE) else "no") and "declared"
            timeouts = "yes" if "timeout-minutes" in text else "**no**"
            retention = "yes" if "retention-days" in text else "**no**"
            summary_step = "yes" if "$GITHUB_STEP_SUMMARY" in text else "**no**"
            shellcheck = "yes" if "shellcheck" in text.lower() else "—"
        rows.append(
            (
                f"`{path.name}`",
                name.strip() if isinstance(name, str) else name,
                triggers,
                perms,
                timeouts,
                retention,
                summary_step,
                shellcheck,
            )
        )

    sec = rep.section("Workflow matrix")
    sec.add("| File | Name | Triggers | Permissions | Timeout | Retention | Step summary | shellcheck |")
    sec.add("| --- | --- | --- | --- | --- | --- | --- | --- |")
    for row in rows:
        sec.add("| " + " | ".join(row) + " |")

    sec = rep.section("Pipeline ↔ workflow drift")
    # Paths the pipeline writes, discovered from src/omnisource
    generated_targets = set()
    for p in iter_files((".py",), trees=("src/omnisource",)):
        for m in re.findall(
            r'(?:pages_dir\s*=\s*container\.paths\.root\s*/\s*"([^"]+)"|"(\w+)"\s*/\s*f"\{[a-z_.]+\}/index\.html"\))',
            read(ROOT / p),
        ):
            generated_targets |= {g for g in m if g}
    allow_paths = set(re.findall(r"'([\w*./ -]+?)'", commit_add)) | set(
        re.findall(r"\n\s+- ([\w*./ -]+)$", commit_add, re.MULTILINE)
    )

    # A tree is "covered" when an allowlist entry names it or one of its real
    # files matches an entry's glob (git's '*.json' pathspec matches at any
    # depth, exactly like fnmatch with a slash-tolerant pattern).
    def covered(directory: str) -> bool:
        stem = directory.rstrip("/")
        if any(stem in str(a) for a in allow_paths):
            return True
        probe = ROOT / directory
        if not probe.is_dir():
            return True  # nothing generated there (yet) — no drift possible
        for path in sorted(probe.rglob("*"))[:400]:
            if not path.is_file():
                continue
            rel_posix = path.relative_to(ROOT).as_posix()
            for pattern in allow_paths:
                if fnmatch.fnmatch(rel_posix, pattern) or fnmatch.fnmatch(path.name, pattern):
                    return True
        return False

    drift = [
        d for d in ("feeds/", "api/", "apps/", "collections/", "compare/", "reports/", "sources/") if not covered(d)
    ]
    if drift:
        for d in drift:
            sec.add(
                f"- ⚠️ pipeline writes into `{d}` but sync.yml commit allowlist does not cover it — scheduled builds would silently fail to publish."
            )
    else:
        sec.add(
            "- No drift: every directory the pipeline publishes (`feeds/`, `api/`, `apps/`, `collections/`, `compare/`, `reports/`, `sources/`) is covered by the sync commit allowlist."
        )
    for wf in workflows:
        for m in re.findall(r"paths:\s*\n((?:\s+-\s+\S+\n)+)", read(wf)):
            for raw in re.findall(r"-\s+([^\s]+)", m):
                glob_path = raw.rstrip("/*")
                if glob_path and not (ROOT / glob_path).exists() and "*" not in raw:
                    sec.add(f"- ⚠️ `{wf.name}` triggers on `{raw}` which does not exist in the repository.")

    sec = rep.section("Obsolescence review")
    sec.add(
        "- `build-tweak.yml` / `build-uyouenhanced.yml`: manual-dispatch IPA builders consumed by the uYouEnhanced catalog entry — retained (functionality), flagged for docs."
    )
    sec.add(
        "- `merge.yml`: safety net for direct `feeds/*.json` edits — retained; duplicates validation but not generation logic."
    )
    sec.add("- `health-check.yml`: schedules daily link probes and files issues — complementary to sync's probe pass.")
    return rep


# --------------------------------------------------------------------------
# Accessibility
# --------------------------------------------------------------------------


class A11yParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.imgs: list[dict] = []
        self.links: list[dict] = []
        self.buttons: list[dict] = []
        self.inputs: list[dict] = []
        self.selects: list[dict] = []
        self.headings: list[tuple[int, str]] = []
        self.ids: list[str] = []
        self.html_attrs: dict = {}
        self.current_heading: int | None = None
        self._skip = False

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        self.ids.append(a.get("id") or "")
        if tag == "html":
            self.html_attrs = a
        elif tag == "img":
            self.imgs.append(a)
        elif tag == "a":
            self.links.append(a)
        elif tag == "button":
            self.buttons.append(a)
        elif tag == "input":
            self.inputs.append(a)
        elif tag == "select":
            self.selects.append(a)
        elif tag in ("h1", "h2", "h3", "h4", "h5", "h6"):
            self.headings.append((int(tag[1]), ""))
        elif tag in ("script", "style"):
            self._skip = True

    def handle_data(self, data):
        if self.headings and not self.headings[-1][1]:
            level, _ = self.headings[-1]
            self.headings[-1] = (level, data.strip()[:60])

    def handle_endtag(self, tag):
        if tag in ("script", "style"):
            self._skip = False


def audit_page(page: Path) -> list[str]:
    text = read(ROOT / page)
    parser = A11yParser()
    with contextlib.suppress(Exception):  # malformed snippets must not abort the audit
        parser.feed(text)
    problems: list[str] = []
    if not parser.html_attrs.get("lang"):
        problems.append("missing `lang` on `<html>`")
    img_total = len(parser.imgs)
    img_unlabeled = [i for i in parser.imgs if "alt" not in i]
    if img_unlabeled:
        problems.append(f"{len(img_unlabeled)}/{img_total} `<img>` without `alt`")
    no_label_buttons = [
        b
        for b in parser.buttons
        if not (
            b.get("aria-label") or b.get("data-i18n-aria-label") or b.get("title") or "close" in (b.get("class") or "")
        )
    ]
    if parser.buttons and len(no_label_buttons) > len(parser.buttons) * 0.6:
        problems.append("most buttons rely on inner text only (screen-reader labels recommended for icon buttons)")
    dup_ids = sorted({i for i in parser.ids if i and parser.ids.count(i) > 1})
    if dup_ids:
        problems.append("duplicate ids: " + ", ".join(f"`{d}`" for d in dup_ids[:6]))
    levels = [lvl for lvl, _t in parser.headings]
    skips = [f"h{a}→h{b}" for a, b in pairwise(levels) if b - a > 1]
    if skips:
        problems.append("heading levels skip: " + ", ".join(sorted(set(skips))[:6]))
    links_without_href = [a for a in parser.links if not a.get("href")]
    if links_without_href:
        problems.append(f"{len(links_without_href)} `<a>` without `href` (use button)")
    bare_newtab = [
        a for a in parser.links if "_blank" in (a.get("target") or "") and "noopener" not in (a.get("rel") or "")
    ]
    if bare_newtab:
        problems.append(f"{len(bare_newtab)} target=_blank links missing rel=noopener")
    inputs_unlabeled = [
        i
        for i in parser.inputs
        if i.get("type") not in ("hidden", "checkbox", "radio", "submit", "button")
        and not (i.get("aria-label") or i.get("data-i18n-aria-label") or i.get("id"))
    ]
    if inputs_unlabeled:
        problems.append(f"{len(inputs_unlabeled)} text inputs without label/aria-label")
    if "skip-link" not in text and "skip link" not in text.lower() and "<main" in text:
        problems.append("no skip link")
    # A `<dialog>` driven by showModal() from a shared script is modal by
    # definition, so the check only fires when no script in the tree opens it.
    if (
        re.search(r"<dialog\b", text)
        and "aria-modal" not in text
        and "showModal" not in text
        and "showModal" not in _shared_js()
    ):
        problems.append("dialog present without modal semantics (verify showModal usage in JS)")
    return problems


@functools.lru_cache(maxsize=1)
def _shared_js() -> str:
    """Concatenated shared client scripts (modal/dialog wiring lives here)."""
    parts = []
    for path in iter_files((".js",), trees=("js", "src/js", "website")):
        parts.append(read(ROOT / path))
    return "\n".join(parts)


def write_accessibility() -> Report:
    rep = Report(
        "Accessibility Audit",
        "Structural WCAG-AA checks run over every hand-maintained HTML page (generated app/collection/\n"
        "source pages are scanned separately by the smoke test markers). Contrast, focus states and\n"
        "motion policy live in the design system and are noted per section.",
    )
    pages = [p for p in html_pages() if not rel(p).startswith(("apps/", "collections/", "sources/"))]
    gen_sample = [p for p in html_pages() if rel(p).startswith(("apps/", "collections/", "sources/"))][:12]
    all_problems: dict[str, list[str]] = {}
    for page in pages + gen_sample:
        problems = audit_page(page)
        if problems:
            all_problems[rel(page)] = problems
    rep.summary.append(f"- Pages scanned: **{len(pages) + len(gen_sample)}**")
    rep.summary.append(f"- Pages with structural findings: **{len(all_problems)}**")

    sec = rep.section("Findings by page")
    if all_problems:
        for page, problems in sorted(all_problems.items()):
            sec.add(f"- `{page}`")
            for p in problems:
                sec.add(f"  - {p}")
    else:
        sec.add(
            "No structural findings — every scanned page declares `lang`, labels its controls, keeps heading order and guards `target=_blank`."
        )

    sec = rep.section("Design-system guarantees")
    sec.add(
        "- `:focus-visible` styles: "
        + ("present" if ":focus-visible" in read(ROOT / "assets/design-system/components.css") else "**missing**")
    )
    anim = read(ROOT / "assets/design-system/animations.css")
    tokens = read(ROOT / "assets/design-system/tokens.css")
    sec.add(
        "- `prefers-reduced-motion` respected in animations.css: "
        + ("yes" if "prefers-reduced-motion" in anim else "**no**")
        + "; tokens.css: "
        + ("yes" if "prefers-reduced-motion" in tokens else "**no**")
    )
    sec.add(
        "- Contrast: status colors (`--green/--amber/--red`) pair with `-soft` surfaces on both themes; verify badge text ≥ 4.5:1 after any palette change (see `tokens.css`)."
    )
    sec.add("- Keyboard: ⌘K palette, dialogs via `<dialog>` + `showModal`, skip links, focus rings.")

    sec = rep.section("Manual verification checklist")
    sec.add("- [ ] Tab through the header nav, filters, palette and dialogs in dark + light themes.")
    sec.add("- [ ] NVDA/VoiceOver pass on the home page (announced live regions update on filter).")
    sec.add("- [ ] Toggle `prefers-reduced-motion` in dev tools: all transforms/orbs must stop.")
    sec.add("- [ ] RTL (Arabic) layout of hero + nav + dialogs.")
    return rep


# --------------------------------------------------------------------------
# Links + SEO
# --------------------------------------------------------------------------


def walk_pages():
    for p in iter_files((".html",)):
        yield p, read(ROOT / p)


def resolve_target(page: Path, href: str) -> tuple[bool, str]:
    """Check an internal href against the served tree (repo root == site root)."""
    href = href.split("#", 1)[0].split("?", 1)[0]
    if not href:
        return True, "anchor"
    base = ROOT / page.parent
    target = (base / href).resolve()
    kind = "file"
    if href.endswith("/"):
        target = target / "index.html"
    if target.exists():
        return True, kind
    # GitHub Pages project site: paths may also live in feeds/api mirrors.
    return False, kind


def write_links() -> Report:
    rep = Report(
        "Links & SEO Audit",
        "Every internal href/src on committed pages is resolved against the repository tree (which is\n"
        "what GitHub Pages serves in branch mode). SEO metadata is checked page-by-page: title,\n"
        "description, canonical, Open Graph, Twitter card.",
    )
    broken: list[str] = []
    seo_missing: dict[str, list[str]] = {}
    external_refs = 0
    for page, text in walk_pages():
        for match in re.finditer(r'(?:href|src|data-feed)="([^"]+)"', text):
            url = match.group(1)
            if not url.startswith(("#", "/OmniSource", "/", "./", "../")):
                # Custom client schemes (altstore://, sidestore://, feather://,
                # esign://, livecontainer://, itms-services://, ...) are not
                # page links — they are handled by the sideloading client.
                external_refs += 1
                continue
            if url.startswith(("http://", "https://", "mailto:", "data:", "javascript:", "//")):
                external_refs += 1
                continue
            if url.startswith("#") or url.startswith("{{") or "${" in url:
                continue  # template-literal paths resolve at runtime
            ok, _kind = resolve_target(page, url)
            if not ok:
                broken.append(f"`{rel(page)}` → `{url}`")
        for match in re.finditer(r"srcset=\"([^\"]+)\"", text):
            for cand in match.group(1).split(","):
                u = cand.strip().split(" ")[0]
                if u and not u.startswith(("http", "//", "data:")):
                    ok, _ = resolve_target(page, u)
                    if not ok:
                        broken.append(f"`{rel(page)}` srcset → `{u}`")
        if "data-page" not in text:  # generated pages without site chrome don't need full SEO kit
            pass
        needs = ["<title", 'name="description"', 'rel="canonical"', 'property="og:title"', 'name="twitter:card"']
        miss = [n for n in needs if n not in text]
        if miss:
            seo_missing[rel(page)] = miss

    # sitemap cross-check
    sitemap_urls = (
        re.findall(r"<loc>([^<]+)</loc>", read(ROOT / "sitemap.xml")) if (ROOT / "sitemap.xml").exists() else []
    )
    base_marker = "/OmniSource/"
    sitemap_missing = []
    for url in sitemap_urls:
        tail = url.split(base_marker, 1)[-1]
        candidate = ROOT / tail if tail else ROOT / "index.html"
        if not candidate.name:
            candidate = candidate / "index.html"
        if not candidate.exists():
            sitemap_missing.append(url)

    rep.summary.append(f"- Broken internal link targets: **{len(set(broken))}**")
    rep.summary.append(
        f"- Pages missing SEO metadata: **{len(seo_missing)}** (of {len(list(walk_pages()))} HTML files)"
    )
    rep.summary.append(f"- Sitemap URLs not resolvable in the tree: **{len(sitemap_missing)}**")
    rep.summary.append(f"- External references (not resolved offline): {external_refs}")

    sec = rep.section("Broken internal links")
    for line in sorted(set(broken))[:60] or [
        "None. Every relative href/src/srcset on every page resolves against the repository tree."
    ]:
        sec.add(f"- {line}")
    if len(set(broken)) > 60:
        sec.add(f"- …and {len(set(broken)) - 60} more.")

    sec = rep.section("SEO metadata gaps")
    if seo_missing:
        sec.add("| Page | Missing |")
        sec.add("| --- | --- |")
        for page, miss in sorted(seo_missing.items()):
            sec.add(f"| `{page}` | {', '.join(f'`{m}`' for m in miss)} |")
    else:
        sec.add("Every scanned page ships title, description, canonical, Open Graph and Twitter card tags.")

    sec = rep.section("Sitemap")
    sec.add(f"- {len(sitemap_urls)} URLs listed in `sitemap.xml`.")
    if sitemap_missing:
        for u in sitemap_missing[:20]:
            sec.add(f"- ⚠️ listed but missing: `{u}`")
    else:
        sec.add("- All listed URLs resolve in the repository tree (branch-deployment mode).")

    sec = rep.section("Redirect/alias notes")
    sec.add(
        "- Extensionless API routes (`/api/apps`, …) ship as committed twin files because Pages cannot rewrite; see `docs/API.md`."
    )
    return rep


# --------------------------------------------------------------------------
# Recommendations
# --------------------------------------------------------------------------


def write_recommendations(findings: dict[str, list]) -> Report:
    rep = Report(
        "Recommendations",
        "Prioritized follow-ups derived from the other reports by `scripts/audit.py`. Items marked\n"
        "**RESOLVED** were addressed during the modernization pass; keep the file as the living\n"
        "worklist — regenerate with `make audit` and prune resolved items when they ship.",
    )
    sec = rep.section("P0 — correctness / publication")
    for line in findings.get("P0", ["- none open"]):
        sec.add(line)
    sec = rep.section("P1 — UX, a11y, i18n")
    for line in findings.get("P1", ["- none open"]):
        sec.add(line)
    sec = rep.section("P2 — performance & repository weight")
    for line in findings.get("P2", ["- none open"]):
        sec.add(line)
    sec = rep.section("P3 — long-term")
    for line in findings.get("P3", ["- none open"]):
        sec.add(line)
    return rep


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------


def compute_findings() -> dict[str, list]:
    """Derive recommendation lines from the current tree state."""
    findings: dict[str, list] = {"P0": [], "P1": [], "P2": [], "P3": []}
    unused_files, _dead_globals, _unused_selectors, dead_python = audit_files_and_globals()
    if unused_files:
        findings["P0"].append(
            f"- Remove or wire the {len(unused_files)} unreferenced file(s) in `dead-code.md` (each is confirmed unused at the commit)."
        )
    if dead_python:
        findings["P0"].append(
            f"- Delete {len(dead_python)} uncalled public function(s) or document them as extension points."
        )
    groups = duplicate_json_groups()
    if groups:
        findings["P2"].append(
            f"- {len(groups)} JSON mirror group(s) remain by design (branch Pages compatibility); do not delete without updating `src/omnisource/site.py`, `publish_root.py` and the smoke test in the same PR. **RESOLVED as accepted technical debt** — documented in `duplicates.md`."
        )
    localization = load_json(Path("feeds/translation-status.json")) or {}
    low = [k for k, v in localization.items() if isinstance(v, int) and v < 100]
    if low:
        findings["P1"].append(
            f"- Locales below 100% coverage: {', '.join(low)} — add the missing keys to `locales/*.json`."
        )
    return findings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--only", choices=("dead", "dup", "l10n", "perf", "wf", "a11y", "links", "recs", "all"), default="all"
    )
    parser.add_argument(
        "--check", action="store_true", help="print a one-line summary and exit non-zero if P0 findings exist"
    )
    args = parser.parse_args(argv)

    REPORTS_DIR.mkdir(exist_ok=True)
    which = args.only
    written: list[str] = []
    if which in ("dead", "all"):
        written.append((_REPORT := REPORTS_DIR / "dead-code.md").name) or _REPORT.write_text(
            write_dead_code().render(), encoding="utf-8"
        )
    if which in ("dup", "all"):
        written.append((_REPORT := REPORTS_DIR / "duplicates.md").name) or _REPORT.write_text(
            write_duplicates().render(), encoding="utf-8"
        )
    if which in ("l10n", "all"):
        written.append((_REPORT := REPORTS_DIR / "localization.md").name) or _REPORT.write_text(
            write_localization().render(), encoding="utf-8"
        )
    if which in ("perf", "all"):
        written.append((_REPORT := REPORTS_DIR / "performance.md").name) or _REPORT.write_text(
            write_performance().render(), encoding="utf-8"
        )
    if which in ("wf", "all"):
        written.append((_REPORT := REPORTS_DIR / "workflows.md").name) or _REPORT.write_text(
            write_workflows().render(), encoding="utf-8"
        )
    if which in ("a11y", "all"):
        written.append((_REPORT := REPORTS_DIR / "accessibility.md").name) or _REPORT.write_text(
            write_accessibility().render(), encoding="utf-8"
        )
    if which in ("links", "all"):
        written.append((_REPORT := REPORTS_DIR / "links.md").name) or _REPORT.write_text(
            write_links().render(), encoding="utf-8"
        )
    findings = compute_findings()
    if which in ("recs", "all"):
        written.append((_REPORT := REPORTS_DIR / "recommendations.md").name) or _REPORT.write_text(
            write_recommendations(findings).render(), encoding="utf-8"
        )

    p0 = len(findings["P0"])
    if args.check:
        print(f"audit: {p0} P0 finding(s)")
        return 1 if p0 else 0
    # Only the files this script owns are listed: reports/final-audit.md is the
    # hand-written modernization summary and must never look auto-generated.
    print("audit: wrote " + ", ".join(sorted(written)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
